#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

bash scripts/validate.sh

cat > docker-compose.yml <<'HEADER'
# Auto-generated by scripts/generate.sh — do not edit
services:
HEADER

for envfile in */.env; do
    [[ -f "$envfile" ]] || continue
    dirname="$(dirname "$envfile")"

    # Source values from .env
    REPO_URL="" RUNNER_TOKEN="" RUNNER_SCOPE="" RUNNER_NAME="" LABELS=""
    CPU_LIMIT="" MEMORY_LIMIT="" RUNNER_WORKDIR=""
    while IFS='=' read -r key val; do
        [[ -z "$key" || "$key" =~ ^# ]] && continue
        key="$(echo "$key" | xargs)"
        val="$(echo "$val" | sed 's/#.*//' | xargs)"
        declare "$key=$val"
    done < "$envfile"

    # Defaults
    CPU_LIMIT="${CPU_LIMIT:-1.0}"
    MEMORY_LIMIT="${MEMORY_LIMIT:-1g}"
    RUNNER_WORKDIR="${RUNNER_WORKDIR:-/tmp/runner/${RUNNER_NAME}}"

    cat >> docker-compose.yml <<EOF
  runner-${dirname}:
    image: myoung34/github-runner:latest
    restart: unless-stopped
    env_file: ${dirname}/.env
    environment:
      RUNNER_WORKDIR: ${RUNNER_WORKDIR}
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: /runner/data/${RUNNER_NAME}
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
          memory: ${MEMORY_LIMIT}
    security_opt:
      - label:disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /runner/data/${RUNNER_NAME}:/runner/data/${RUNNER_NAME}
      - ${RUNNER_WORKDIR}:${RUNNER_WORKDIR}
EOF
done

echo "Generated docker-compose.yml"
